### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by mattbk** [hmngwy/weblog.sh#1]
> matt@matt-VirtualBox:~$ weblog help
> /home/matt/./weblog.sh: 16: /home/matt/./weblog.sh: Syntax error: "(" unexpected

No errors during install operations at https://weblog.sh/, until this point.

Ubuntu 14.04 in VirtualBox.

**Comment by mattbk** [comment]
According to [this](http://ubuntuforums.org/showthread.php?t=499045&p=3006552#post3006552), it's an Ubuntu issue.

Solution that worked for me:

> or replace first line with: #!/bin/bash

**Comment by hmngwy** [comment]
hey @mattbk, that's completely my bad, it should say bash instead of sh, thanks!
