### ISSUE TITLE
Unable to login with password auth

### ISSUE THREAD

**Issue by mrbalihai** [hmngwy/weblog.sh#14]
I created and tried to login with two separate accounts (rob, robbollons) and it failed to log me in with 'Permission denied'. I tried with a third account (rob2) but used a shorter/simpler password and this seemed to work. 
My TERM is: screen-256color

**Comment by hmngwy** [comment]
How can I better emulate your setup?

I couldn't replicate with `screen` while `echo "term screen-256color" > ~/.screenrc`.

**Comment by mrbalihai** [comment]
Yes sorry, I should have mentioned I'm running bash inside tmux. My term is set in my bashrc as `export TERM='screen-256color'`, nothing is set in my tmux.conf.

**Comment by hmngwy** [comment]
Hmm, I tried `tmux`+`bash` (on a mac) and have nothing in my .bashrc other than `export TERM='screen-256color'`, I used a variety of characters and can't replicate the problem.

**Comment by mrbalihai** [comment]
I just tried it again by creating a rob3 account and it worked..., I'm very sorry, I guess I just need more coffee. I appreciate you looking into this anyway. FYI I've created a bunch of useless accounts now: rob, robbollons, rob2 and rob3, I don't know if you'd want to clean them up. Thanks!
