### ISSUE TITLE
Losing connection on bulk upload

### ISSUE THREAD

**Issue by marksteve** [hmngwy/weblog.sh#18]
```
scp *.md weblog.sh:public/                                                                    ~/Projects/Github/marksteve/til
2015-02-19.md                                                                                              100%  641     0.6KB/s   00:00
lost connection
```

Close if this was by design

**Comment by marksteve** [comment]
`ls *.md | xargs -I % scp % weblog.sh:public/`

**Comment by hmngwy** [comment]
At the current response rate of the server, I don't recommend bulk uploads, but we should still be able to do it. So if you decide to use this, please `sleep` at least a couple or more seconds between requests.
