### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by achikin** [hmngwy/weblog.sh#21]
Hi! Super cool idea, but I can't create an account with username 'blinkenlights' for some reason.

```
→ Account creation failed, kindly try again.

Connection to weblog.sh closed.
```

**Comment by hmngwy** [comment]
@achikin usernames are tested against /^[a-z0-9]{2,12}$/, max of 12 characters, minimum of 2. I'll make the error messages more verbose. 

Bit of fair warning too, user registration flow will change soon: See #10.
