### ISSUE TITLE
Anyone having issues saving markdown files?

### ISSUE THREAD

**Issue by sedusa** [hmngwy/weblog.sh#24]
Hi guys,
I get a strange `Article does not exist.` message when I try to publish a markdown file.  Has anyone run into this problem? Not having any issues publishing text files though.
Great job @hmngwy !

Thanks

**Comment by pscollins** [comment]
Can you put the exact text of your post up on a gist or something similar? (I say a gist rather than in here because the whitespace needs to be preserved exactly, and GitHub's markdown parser might take out useful info)

**Comment by hmngwy** [comment]
Hmm.. as long as the .md file has a title, i.e. minimum of "# Hello" (note the space after #), the file should get saved. 

@sedusa, I'm interested in seeing the same request above. And thanks btw!

**Comment by sedusa** [comment]
Thanks @hmngwy and @pscollins  for the responses. Can't believe I forgot to add the space after my H1 title. Silly me! Everything works fine.

**Comment by hmngwy** [comment]
I see, yeah it's a bit unintuitive but it's a markdown thing, some parsers/editors allow it, but then you can't have sentences that start with something like `#1`, so most libraries require the space there.
