### ISSUE TITLE
Static Assets

### ISSUE THREAD

**Issue by andrewdunndev** [hmngwy/weblog.sh#26]
Is weblog.sh going to be purely text\* assets with expected external linking to things such as images? If not, whats the preferred method of pushing up static assets.

*I am ok with weblog.sh being purely text. I quite like the simplicity of it.

**Comment by pscollins** [comment]
Based on the talk about minimalism in #3, I'd say that it's intended to remain pure text. Allowing uploads of images would probably jack up hosting costs, too. Let's see what the author says.

**Comment by howdoicomputer** [comment]
What about just hosting the images somewhere else then linking them in via markdown?

**Comment by hmngwy** [comment]
@storrgie weblog.sh will only host pages keeping in line with its agenda. @howdoicomputer's suggestion should suffice. :)

**Comment by andrewdunndev** [comment]
@hmngwy I'm totally ok with that, but do you mind writing out what the agenda is? Maybe add a footnote or link to 'simple' in the 'Simple and anonymous.' line where you have a page listing out the 'axioms' of simple.

I think its a good choice to only host text.

**Comment by hmngwy** [comment]
From the [about page](https://weblog.sh/about): 

"To have the ability get a thought out and fast, and _to present passages in its most basic form_ in hope that its thought would carry it alone."

P.S. I've yet to update that page after implementing the SSH server, so some text like "CLI client" will not make sense anymore.

**Comment by howdoicomputer** [comment]
To note, there aren't a lot of anonymous storage options out so there is a chance that you'll leave a trail. Oh, and the ones that are somewhat anonymous don't persist their images for a long time.
