### ISSUE TITLE
Trying to upload SSH key. Original password not recognized.

### ISSUE THREAD

**Issue by ghost** [hmngwy/weblog.sh#27]
I'm not sure if this is the right place. If it's not, I apologize in advance.

I registered as **megadriver** a week ago, when SSH keys were still optional, but didn't do anything else after that. Now I've been trying to upload an SSH key in order to start blogging, but when it asks for my password, it's not being recognized, so I can't do anything. I'm 100% positive I'm typing the same password I originally used to register. I'd really want to keep **megadriver** as my user name, if possible. Thanks.

**Comment by megadrivers** [comment]
That's weird. Looks like my password is being accepted now. I've posted something, but it's not appearing online.

**Comment by megadrivers** [comment]
Oops. I accidentally closed this. Reopening.

I tried again and now it looks like my password was accepted. However, I've tried writing and then publishing a post, but nothing appears online. I'm a bit confused.

**Comment by megadrivers** [comment]
Back to the original problem. It still asks for my password, and again it's not being recognized.

**Comment by hmngwy** [comment]
Password logins should still work despite registrations are now key-only.

**Comment by hmngwy** [comment]
@megadrivers ok I looked at the time you registered, you were affected by a registration bug, email me using the link at the footer of the homepage so we can work on account recovery.

**Comment by ghost** [comment]
(ﾉ´ヮ´)ﾉ*:･ﾟ✧
