### ISSUE TITLE
wordpress migration

### ISSUE THREAD

**Issue by norayr** [hmngwy/weblog.sh#33]
did i miss it, or there is no wp migration mechanism available?

wordpress is able to export xml file, is it possible to import somehow to weblog.sh ?

**Comment by hmngwy** [comment]
No, none currently/planned. Though someone was able to `scp` a directory
full of files and it worked ok after adding a sleep in between each upload.

Maybe use `xmllint` to parse your XML file and write into separate files,
and then `scp` them.

**Comment by norayr** [comment]
thank you.
