### ISSUE TITLE
Categories aka subfolders

### ISSUE THREAD

**Issue by Radiergummi** [hmngwy/weblog.sh#35]
Would it be possible to implement a `mkdir` command that lets users create subfolders withing their home directory? These would map to the blog entry url.

Example:  
`ssh walt@weblog.ssh mkdir my-super-awesome-cat`  
`scp example.md walt@weblog.sh:public/my-super-awesome-cat/`  
`curl http://weblog.sh/~walt/my-super-awesome-cat/example // yayyy!`

**Comment by hmngwy** [comment]
Unfortunately this will diminish the minimalist design, it is not a bad idea though.
