### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by hmngwy** [hmngwy/weblog.sh#8]

**Comment by neeasade** [comment]
perhaps of note: http://git.z3bra.org/cgit.cgi/monochromatic/tree/tomarkdown.sed

**Comment by hmngwy** [comment]
The endpoint stores the raw file in a different field (from the processed string), so I can just send that back to the user without any pre-processing, instead of converting html to markdown/plain and back.

P.S. though it's really beautiful that you can do this with sed. 👍

**Comment by james-see** [comment]
Would really like this unless there is a way to also just read and convert regular html? I tried doing h tags and others and it renders them literally.

**Comment by hmngwy** [comment]
There is currently alpha support of Markdown. Simply name your files with a
.md extension. The H1 (or #) will be the title.

**Comment by james-see** [comment]
Ah, that makes perfect sense. I'll try it out. Thanks!

**Comment by james-see** [comment]
I tried it and it works great. Using gratipay to micro-support as much as I can which is very minimal right now. Cheers.

**Comment by hmngwy** [comment]
Thanks @jamesacampbell! Every bit helps.

**Comment by GSI** [comment]
I wonder why "Markdown support!!" is always the first thing called for in such projects. Textile is much easier and intuitive, while being just as powerful.

I guess most MD-fanatics simply never heard of Textile. Cannot think of any other logical reason;

**Comment by hmngwy** [comment]
Speaking of markdown, markdown support applied a few commits back, closing.
